version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      next:
        patterns:
          - "next"
          - "react"
          - "react-dom"
    open-pull-requests-limit: 10
